# Generated by Django 6.1.1 on 2026-09-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        ('usuarios', '0009_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.solicitud'),
        ),
    ]
