# Generated by Django 6.1.1 on 2026-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(choices=[('plomeria', 'Plomería'), ('electricidad', 'Electricidad'), ('tecnologia', 'Tecnología'), ('limpieza', 'Limpieza'), ('mascotas', 'Mascotas'), ('abogados', 'Abogados'), ('construccion', 'Construcción')], default='plomeria', max_length=30),
            preserve_default=False,
        ),
    ]
