# Generated by Django 6.1.1 on 2026-09-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_servicio_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_profesional',
            field=models.BooleanField(default=False),
        ),
    ]
