# Generated by Django 6.1.1 on 2026-09-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_profesional',
            field=models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
