# Generated by Django 6.1.1 on 2026-09-20 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_estado_profesional_usuario_saldo_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comision_in_talent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='estado_pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='precio_acordado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='valor_profesional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
