# Generated by Django 6.1.1 on 2026-09-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_solicitud_comision_in_talent_solicitud_estado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada'), ('confirmada', 'Confirmada')], default='pendiente', max_length=20),
        ),
    ]
